//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleServiceClient.RESTfulService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/RESTfulWcfService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RESTfulService.IRESTfulService")]
    public interface IRESTfulService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESTfulService/HelloWorld", ReplyAction="http://tempuri.org/IRESTfulService/HelloWorldResponse")]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESTfulService/HelloWorld", ReplyAction="http://tempuri.org/IRESTfulService/HelloWorldResponse")]
        System.Threading.Tasks.Task<string> HelloWorldAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESTfulService/GetEnumerableOfInt", ReplyAction="http://tempuri.org/IRESTfulService/GetEnumerableOfIntResponse")]
        int[] GetEnumerableOfInt();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESTfulService/GetEnumerableOfInt", ReplyAction="http://tempuri.org/IRESTfulService/GetEnumerableOfIntResponse")]
        System.Threading.Tasks.Task<int[]> GetEnumerableOfIntAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESTfulService/GetData", ReplyAction="http://tempuri.org/IRESTfulService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESTfulService/GetData", ReplyAction="http://tempuri.org/IRESTfulService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESTfulService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IRESTfulService/GetDataUsingDataContractResponse")]
        ConsoleServiceClient.RESTfulService.CompositeType GetDataUsingDataContract(ConsoleServiceClient.RESTfulService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRESTfulService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IRESTfulService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<ConsoleServiceClient.RESTfulService.CompositeType> GetDataUsingDataContractAsync(ConsoleServiceClient.RESTfulService.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRESTfulServiceChannel : ConsoleServiceClient.RESTfulService.IRESTfulService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RESTfulServiceClient : System.ServiceModel.ClientBase<ConsoleServiceClient.RESTfulService.IRESTfulService>, ConsoleServiceClient.RESTfulService.IRESTfulService {
        
        public RESTfulServiceClient() {
        }
        
        public RESTfulServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RESTfulServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RESTfulServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RESTfulServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public System.Threading.Tasks.Task<string> HelloWorldAsync() {
            return base.Channel.HelloWorldAsync();
        }
        
        public int[] GetEnumerableOfInt() {
            return base.Channel.GetEnumerableOfInt();
        }
        
        public System.Threading.Tasks.Task<int[]> GetEnumerableOfIntAsync() {
            return base.Channel.GetEnumerableOfIntAsync();
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public ConsoleServiceClient.RESTfulService.CompositeType GetDataUsingDataContract(ConsoleServiceClient.RESTfulService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<ConsoleServiceClient.RESTfulService.CompositeType> GetDataUsingDataContractAsync(ConsoleServiceClient.RESTfulService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
